"""my_new_feature

Revision ID: 37c8c544218f
Revises: 5c844a56a641
Create Date: 2025-01-26 14:39:42.616567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37c8c544218f'
down_revision = '5c844a56a641'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
